name: Wake up Streamlit App

on:
  schedule:
    # හැම විනාඩි 15 කට වරක්ම ක්‍රියාත්මක වේ
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App to keep alive
        run: |
          curl -L --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://killzone-ai-achuwybnjnppic3divrneh.streamlit.app/
